const fs=require('fs'),path=require('path');
const puppeteer=require('D:/Work/Codex/Hackathon Projects/LumaLoad/node_modules/puppeteer');
const dir=__dirname,sleep=ms=>new Promise(r=>setTimeout(r,ms));
const timeline=JSON.parse(fs.readFileSync(path.join(dir,'timeline.json'),'utf8'));
async function click(p,text){await p.waitForFunction(t=>[...document.querySelectorAll('button')].some(x=>x.innerText.includes(t)&&!x.disabled),{timeout:45000},text);for(const b of await p.$$('button')){if(await b.evaluate((x,t)=>x.innerText.includes(t)&&!x.disabled,text)){await b.evaluate(x=>x.scrollIntoView({block:'center',behavior:'smooth'}));await sleep(400);await b.click();return;}}throw Error(text);}
(async()=>{const browser=await puppeteer.launch({headless:true});const p=await browser.newPage();await p.setViewport({width:1920,height:1080});p.on('pageerror',e=>console.log('PAGE ERROR',e.message));await p.goto('https://schoolbag-afh.vercel.app',{waitUntil:'networkidle2'});await p.waitForFunction(()=>document.body.innerText.includes('PostgreSQL'),{timeout:60000});
const cdp=await p.createCDPSession();let current=null,counter=0;cdp.on('Page.screencastFrame',async e=>{if(current){const file=path.join(current.folder,`${String(counter++).padStart(6,'0')}.jpg`);fs.writeFileSync(file,Buffer.from(e.data,'base64'));current.frames.push({file,t:(Date.now()-current.start)/1000});}await cdp.send('Page.screencastFrameAck',{sessionId:e.sessionId});});
await cdp.send('Page.startScreencast',{format:'jpeg',quality:88,everyNthFrame:1});
async function scene(id,work){const s=timeline.find(x=>x.id===id),folder=path.join(dir,'capture',id);fs.mkdirSync(folder,{recursive:true});current={folder,frames:[],start:Date.now()};await p.screenshot({path:path.join(folder,'initial.jpg')});current.frames.push({file:path.join(folder,'initial.jpg'),t:0});await work();const elapsed=(Date.now()-current.start)/1000;if(elapsed>s.sceneDuration)throw Error(`Scene ${id} exceeded narration: ${elapsed}`);await sleep((s.sceneDuration-elapsed)*1000);fs.writeFileSync(path.join(folder,'manifest.json'),JSON.stringify({duration:s.sceneDuration,frames:current.frames}));current=null;console.log('Recorded',id);}
await scene('02-intake',async()=>{await sleep(3000);await click(p,'Ingest School Notice');await click(p,'Kavya:');await sleep(6000);await p.click('button[type=submit]');await p.waitForFunction(()=>!document.querySelector('.modal-backdrop'),{timeout:25000});await sleep(3000);});
await scene('03-advice',async()=>{await click(p,'Analyze with Strands AI');await p.waitForFunction(()=>!document.body.innerText.includes('Analyzing with Strands AI...'),{timeout:28000});await sleep(1500);console.log((await p.$eval('body',e=>e.innerText)).slice(-6500));});
await scene('04-control',async()=>{await click(p,'Simulate Assistant Approval');await sleep(4000);await click(p,'Parent Sign');await sleep(4000);await click(p,'Mark Completed');await sleep(3000);});
await scene('05-family',async()=>{await click(p,'Ingest School Notice');await click(p,'Arun:');await sleep(2500);await p.click('button[type=submit]');await p.waitForFunction(()=>!document.querySelector('.modal-backdrop'),{timeout:20000});await click(p,'Family Weekly Board');await sleep(4000);await p.screenshot({path:path.join(dir,'family-board.png')});});
await cdp.send('Page.stopScreencast');await browser.close();})();
